server:
  # 禁用 Spring 生成404等错误信息，返回到前台
  error:
    whitelabel:
      enabled: false
  port: 8082
  tomcat:
    uri-encoding: UTF-8
  #servlet:
    #context-path: /config
spring:
  # JSON相关配置
  jackson:
    locale: zh_CN
    default-property-inclusion: non-null
  # Config Server相关配置  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/firechiang/springcloud-test-configs.git
          username: firechiang
          password: dsfksdfnksdnfsd # 公共的仓库可以不用用户名和密码
          # basedir: /Users/admin/code/myProjects/java/imooc/SpringCloud_Sell/config/basedir  配置文件下载后所在目录
          
# 配置服务配置文件访问说明（注意：配置文件也要按照如下方式进行命名）
# /{name}-{profiles}.yml  
# /{label}/{name}-{profiles}.yml  

# name=服务名称
# profiles=环境
# label=配置文件所在git分支，不写默认就是master分支（当然不用git也就没有分支一说）  

# 日志级别相关      
logging:
  level:
    com.firecode.elktest.biz.dao: debug
    org.hibernate.SQL: debug
# 开启全局debug日志    
#debug: true